### ISSUE TITLE
parray_gin_ops index fails sometimes

### ISSUE THREAD

**Issue by pidupuis** [theirix/parray_gin#1]
Basically for a query using `'%a%'` which normally returns the entire table, I obtain 0 row since I created the index. And for a query using `'%fam%'` (which logically include the results using `'%a%'`) I obtain the entire table as expected.

So the index seems to be working on long patterns (with less matches) but not on short patterns (which matches more).

**Comment by theirix** [comment]
Fixed by #3, forgot to close.
