### ISSUE TITLE
please fix warnings to allow compiling under clang-16 (debian12)

### ISSUE THREAD

**Issue by justinpryzby** [theirix/parray_gin#11]
Currently the build fails due to -Werror.

src/parray_gin.c:598:33: warning: incompatible integer to pointer conversion passing 'int32' (aka 'int') to parameter of type 'const void *' [-Wint-conversion]
                                                                                                           PointerGetDatum(key1),
src/parray_gin.c:599:31: warning: incompatible integer to pointer conversion passing 'int32' (aka 'int') to parameter of type 'const void *' [-Wint-conversion]
                                                                                                         PointerGetDatum(key2)));

There's other warnings that ought to be addressed, not sure if it's useful, but I'll include them here:

src/parray_gin.c:311:54: warning: passing argument 1 of ‘DatumGetPointer’ makes integer from pointer without a cast [-Wint-conversion]
src/parray_gin.c:311:40: warning: incompatible pointer to integer conversion passing 'text *' (aka 'struct varlena *') to parameter of type 'Datum' (aka 'unsigned long') [-Wint-conversion]

**Comment by justinpryzby** [comment]
Until then, here's a workaround
sudo 'PG_CPPFLAGS=-Wno-int-conversion' PATH=/usr/lib/postgresql/16/bin:$PATH pgxnclient install parray_gin

**Comment by theirix** [comment]
Hello! Thank you for the report. I've switched build images to Docker 12. I will fix the compilation problems

**Comment by theirix** [comment]
Should be fixed in version 1.3.9 (release on pgxn and tagged in Github repo)

**Comment by justinpryzby** [comment]
Confirmed, thanks a lot !
