### ISSUE TITLE
How can I build this on macOS?

### ISSUE THREAD

**Issue by ir-fuel** [theirix/parray_gin#5]
When compiling on macOS, with PostgreSQL 10 installed I always get

```
In file included from src/trgm.c:11:
In file included from /Library/PostgreSQL/10/include/postgresql/server/tsearch/ts_locale.h:18:
/Library/PostgreSQL/10/include/postgresql/server/utils/pg_locale.h:19:10: fatal error: 'unicode/ucol.h' file not found
#include <unicode/ucol.h>
```

I did `brew install icu4c` but it seems the paths are 
```
LDFLAGS= -L/usr/local/opt/icu4c/lib
CPPFLAGS="-I/usr/local/opt/icu4c/include"
```

and I have no idea how to pass them to the compiler.

**Comment by theirix** [comment]
Have you tried to add them to PG_CPPFLAGS and SHLIB_LINK to `Makefile`?
For example,
```
PG_CPPFLAGS = "-I/usr/local/opt/icu4c/include"
SHLIB_LINK =  "-L/usr/local/opt/icu4c/lib"
```

**Comment by ir-fuel** [comment]
Aha, that seems to have worked. But you have to manually download and build this extension. You can't install it using pgxn

**Comment by theirix** [comment]
You are right. I don't remember how platform-specific flags should be handled in Makefile.

**Comment by ir-fuel** [comment]
Guess this can be closed since it works. Maybe add this info to the readme?

**Comment by theirix** [comment]
Added some instructions. Thank for the tip!

**Comment by ir-fuel** [comment]
Thanks for the quick reply btw. Would never have found this myself!
