### ISSUE TITLE
please support postgres 14

### ISSUE THREAD

**Issue by justinpryzby** [theirix/parray_gin#8]
The macros is renamed since this commit.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=8e1f37c07aafd4bb7aa6e1e1982010af11f8b5c7

git diff -w /usr/pgsql-1[34]/include/server/utils/fmgroids.h
-#define F_TEXT_TO_ARRAY_NULL 376
+#define F_STRING_TO_ARRAY_TEXT_TEXT_TEXT 376

**Comment by theirix** [comment]
Thanks for reporting. Fixed and released the version 1.3.3 on PGXN.

**Comment by justinpryzby** [comment]
Thanks!

I think there may be an omission.  I recently added a nagios check that the extensions are upgraded when possible.
ts=# SELECT * FROM pg_available_extensions WHERE installed_version != default_version;
name              | parray_gin
default_version   | 1.3.3
installed_version | 1.3.1
comment           | PostgreSQL GIN support for arrays with partial match

ts=# ALTER EXTENSION parray_gin UPDATE;
ERROR:  extension "parray_gin" has no update path from version "1.3.1" to version "1.3.3"

I guess you should include an empty upgrade script (or maybe the extension version visible to postgres shouldn't have been changed just to add support for pg14?).

**Comment by theirix** [comment]
@justinpryzby thank you for your feedback. I added an upgrade script in 1.3.4. It will help upgrade from 1.3.1 at least. 
Unfortunately, there is no way to use an "empty" upgrade, it's needed to add an explicit script each time. Not a lot of work, of course. 

Tried with 1) `pgxn install parray_gin` and 2) `ALTER EXTENSION parray_gin UPDATE` inside psql, works fine.

**Comment by justinpryzby** [comment]
Thank you.  I confirmed this works.
